<?xml version="1.0" encoding="utf-8"?>
<TestRun id="391d78ae-a40e-4d6c-b2b7-12abfbdbdf1a" name="anna@cloudtest-win10 2023-01-22 23:12:45" runUser="cloudtest-win10\anna" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <Times creation="2023-01-22T23:12:45.3616070+00:00" queuing="2023-01-22T23:12:45.3616076+00:00" start="2023-01-22T23:12:39.0522560+00:00" finish="2023-01-22T23:12:45.4019895+00:00" />
  <TestSettings name="default" id="313794cc-8af5-476a-a214-e1822000b143">
    <Deployment runDeploymentRoot="anna_cloudtest-win10_2023-01-22_23_12_45" />
  </TestSettings>
  <Results>
    <UnitTestResult executionId="f8ef07d0-59d9-4dde-ba3b-df5fe42e58f7" testId="f16aa026-a4b0-5ea6-8637-84dd3952addc" testName="Tester.AzureUtils.AzureQueueDataManagerTests.AQ_Standalone_1" computerName="cloudtest-win10" duration="00:00:01.1739332" startTime="2023-01-22T23:12:45.0438576+00:00" endTime="2023-01-22T23:12:45.0439149+00:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Failed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="f8ef07d0-59d9-4dde-ba3b-df5fe42e58f7">
      <Output>
        <ErrorInfo>
          <Message>Assert.Equal() Failure&#xD;
Expected: 1&#xD;
Actual:   2</Message>
          <StackTrace>   at Tester.AzureUtils.AzureQueueDataManagerTests.AQ_Standalone_1() in C:\Users\anna\orleans\test\Extensions\TesterAzureUtils\AzureQueueDataManagerTests.cs:line 55&#xD;
--- End of stack trace from previous location ---</StackTrace>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
  </Results>
  <TestDefinitions>
    <UnitTest name="Tester.AzureUtils.AzureQueueDataManagerTests.AQ_Standalone_1" storage="c:\users\anna\orleans\test\extensions\testerazureutils\bin\debug\net7.0\tester.azureutils.dll" id="f16aa026-a4b0-5ea6-8637-84dd3952addc">
      <Execution id="f8ef07d0-59d9-4dde-ba3b-df5fe42e58f7" />
      <TestMethod codeBase="C:\Users\anna\orleans\test\Extensions\TesterAzureUtils\bin\Debug\net7.0\Tester.AzureUtils.dll" adapterTypeName="executor://xunit/VsTestRunner2/netcoreapp" className="Tester.AzureUtils.AzureQueueDataManagerTests" name="AQ_Standalone_1" />
    </UnitTest>
  </TestDefinitions>
  <TestEntries>
    <TestEntry testId="f16aa026-a4b0-5ea6-8637-84dd3952addc" executionId="f8ef07d0-59d9-4dde-ba3b-df5fe42e58f7" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
  </TestEntries>
  <TestLists>
    <TestList name="Results Not in a List" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="All Loaded Results" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <ResultSummary outcome="Failed">
    <Counters total="1" executed="1" passed="0" failed="1" error="0" timeout="0" aborted="0" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" completed="0" inProgress="0" pending="0" />
    <Output>
      <StdOut>[xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.4.5+1caef2f33e (64-bit .NET 7.0.2)&#xD;
[xUnit.net 00:00:01.28]   Discovering: Tester.AzureUtils (method display = ClassAndMethod, method display options = None)&#xD;
[xUnit.net 00:00:01.49]   Discovered:  Tester.AzureUtils (found 246 test cases)&#xD;
[xUnit.net 00:00:01.51]   Starting:    Tester.AzureUtils (parallel test collections = off, max threads = 4)&#xD;
[xUnit.net 00:00:02.98]       Assert.Equal() Failure&#xD;
[xUnit.net 00:00:02.98]       Expected: 1&#xD;
[xUnit.net 00:00:02.98]       Actual:   2&#xD;
[xUnit.net 00:00:02.98]       Stack Trace:&#xD;
[xUnit.net 00:00:02.98]         C:\Users\anna\orleans\test\Extensions\TesterAzureUtils\AzureQueueDataManagerTests.cs(55,0): at Tester.AzureUtils.AzureQueueDataManagerTests.AQ_Standalone_1()&#xD;
[xUnit.net 00:00:02.98]         --- End of stack trace from previous location ---&#xD;
[xUnit.net 00:00:03.02]   Finished:    Tester.AzureUtils&#xD;
</StdOut>
    </Output>
    <RunInfos>
      <RunInfo computerName="cloudtest-win10" outcome="Min" timestamp="2023-01-22T23:12:45.0391479+00:00">
        <Text>[xUnit.net 00:00:02.98]     Tester.AzureUtils.AzureQueueDataManagerTests.AQ_Standalone_1 [FAIL]</Text>
      </RunInfo>
      <RunInfo computerName="cloudtest-win10" outcome="Warning" timestamp="2023-01-22T23:12:45.2138876+00:00">
        <Text>Data collector 'Blame' message: All tests finished running, Sequence file will not be generated.</Text>
      </RunInfo>
    </RunInfos>
  </ResultSummary>
</TestRun>