<?xml version="1.0" encoding="utf-8"?>
<TestRun id="d88044db-f41b-46fd-9be7-c822ebea0d0a" name="anna@cloudtest-win10 2023-01-22 18:32:14" runUser="cloudtest-win10\anna" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <Times creation="2023-01-22T18:32:14.5121495+00:00" queuing="2023-01-22T18:32:14.5121498+00:00" start="2023-01-22T18:32:05.0119474+00:00" finish="2023-01-22T18:32:14.5517288+00:00" />
  <TestSettings name="default" id="e94d1705-e112-4a94-b35f-258a8aafb3ff">
    <Deployment runDeploymentRoot="anna_cloudtest-win10_2023-01-22_18_32_14" />
  </TestSettings>
  <Results>
    <UnitTestResult executionId="eb4c0d3f-fafd-4a9d-8be5-4e08cbbf0155" testId="25cf1ab5-8c91-2cb3-44d4-300ca8f4cbf6" testName="Tester.AzureUtils.AzureMembershipTableTests.MembershipTable_Azure_UpdateRowInParallel" computerName="cloudtest-win10" duration="00:00:03.6533104" startTime="2023-01-22T18:32:14.1730426+00:00" endTime="2023-01-22T18:32:14.1730874+00:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Failed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="eb4c0d3f-fafd-4a9d-8be5-4e08cbbf0155">
      <Output>
        <ErrorInfo>
          <Message>System.InvalidOperationException : Sequence contains no matching element</Message>
          <StackTrace>   at System.Linq.ThrowHelper.ThrowNoMatchException()&#xD;
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)&#xD;
   at UnitTests.MembershipTests.MembershipTableTestsBase.MembershipTable_UpdateRowInParallel(Boolean extendedProtocol) in C:\Users\anna\orleans\test\TesterInternal\MembershipTests\MembershipTableTestsBase.cs:line 368&#xD;
   at Tester.AzureUtils.AzureMembershipTableTests.MembershipTable_Azure_UpdateRowInParallel() in C:\Users\anna\orleans\test\Extensions\TesterAzureUtils\AzureMembershipTableTests.cs:line 100&#xD;
--- End of stack trace from previous location ---</StackTrace>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
  </Results>
  <TestDefinitions>
    <UnitTest name="Tester.AzureUtils.AzureMembershipTableTests.MembershipTable_Azure_UpdateRowInParallel" storage="c:\users\anna\orleans\test\extensions\testerazureutils\bin\debug\net7.0\tester.azureutils.dll" id="25cf1ab5-8c91-2cb3-44d4-300ca8f4cbf6">
      <Execution id="eb4c0d3f-fafd-4a9d-8be5-4e08cbbf0155" />
      <TestMethod codeBase="C:\Users\anna\orleans\test\Extensions\TesterAzureUtils\bin\Debug\net7.0\Tester.AzureUtils.dll" adapterTypeName="executor://xunit/VsTestRunner2/netcoreapp" className="Tester.AzureUtils.AzureMembershipTableTests" name="MembershipTable_Azure_UpdateRowInParallel" />
    </UnitTest>
  </TestDefinitions>
  <TestEntries>
    <TestEntry testId="25cf1ab5-8c91-2cb3-44d4-300ca8f4cbf6" executionId="eb4c0d3f-fafd-4a9d-8be5-4e08cbbf0155" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
  </TestEntries>
  <TestLists>
    <TestList name="Results Not in a List" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="All Loaded Results" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <ResultSummary outcome="Failed">
    <Counters total="1" executed="1" passed="0" failed="1" error="0" timeout="0" aborted="0" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" completed="0" inProgress="0" pending="0" />
    <Output>
      <StdOut>[xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.4.5+1caef2f33e (64-bit .NET 7.0.2)&#xD;
[xUnit.net 00:00:01.27]   Discovering: Tester.AzureUtils (method display = ClassAndMethod, method display options = None)&#xD;
[xUnit.net 00:00:01.48]   Discovered:  Tester.AzureUtils (found 246 test cases)&#xD;
[xUnit.net 00:00:01.49]   Starting:    Tester.AzureUtils (parallel test collections = off, max threads = 4)&#xD;
[xUnit.net 00:00:06.19]       System.InvalidOperationException : Sequence contains no matching element&#xD;
[xUnit.net 00:00:06.19]       Stack Trace:&#xD;
[xUnit.net 00:00:06.19]            at System.Linq.ThrowHelper.ThrowNoMatchException()&#xD;
[xUnit.net 00:00:06.19]            at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)&#xD;
[xUnit.net 00:00:06.19]         C:\Users\anna\orleans\test\TesterInternal\MembershipTests\MembershipTableTestsBase.cs(368,0): at UnitTests.MembershipTests.MembershipTableTestsBase.MembershipTable_UpdateRowInParallel(Boolean extendedProtocol)&#xD;
[xUnit.net 00:00:06.19]         C:\Users\anna\orleans\test\Extensions\TesterAzureUtils\AzureMembershipTableTests.cs(100,0): at Tester.AzureUtils.AzureMembershipTableTests.MembershipTable_Azure_UpdateRowInParallel()&#xD;
[xUnit.net 00:00:06.19]         --- End of stack trace from previous location ---&#xD;
[xUnit.net 00:00:06.23]   Finished:    Tester.AzureUtils&#xD;
</StdOut>
    </Output>
    <RunInfos>
      <RunInfo computerName="cloudtest-win10" outcome="Min" timestamp="2023-01-22T18:32:14.1682064+00:00">
        <Text>[xUnit.net 00:00:06.19]     Tester.AzureUtils.AzureMembershipTableTests.MembershipTable_Azure_UpdateRowInParallel [FAIL]</Text>
      </RunInfo>
      <RunInfo computerName="cloudtest-win10" outcome="Warning" timestamp="2023-01-22T18:32:14.3598810+00:00">
        <Text>Data collector 'Blame' message: All tests finished running, Sequence file will not be generated.</Text>
      </RunInfo>
    </RunInfos>
  </ResultSummary>
</TestRun>