<?xml version="1.0" encoding="utf-8"?>
<TestRun id="19a5894f-863c-4e6e-bb33-a7d65683dd46" name="anna@cloudtest-win10 2023-01-22 17:45:38" runUser="cloudtest-win10\anna" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <Times creation="2023-01-22T17:45:38.8330423+00:00" queuing="2023-01-22T17:45:38.8330428+00:00" start="2023-01-22T17:45:03.0295551+00:00" finish="2023-01-22T17:45:52.5495285+00:00" />
  <TestSettings name="default" id="d18733f6-e321-4c01-81b4-c3d0e930eab5">
    <Deployment runDeploymentRoot="anna_cloudtest-win10_2023-01-22_17_45_38" />
  </TestSettings>
  <Results>
    <UnitTestResult executionId="55856235-ad6b-4b3a-bba8-3c0bb00900c1" testId="0ead2138-2212-aba4-35b8-60be64e9d95f" testName="Tester.AzureUtils.TimerTests.ReminderTests_AzureTable.Rem_Azure_Basic_ListOps" computerName="cloudtest-win10" duration="00:00:26.4028757" startTime="2023-01-22T17:45:38.1732107+00:00" endTime="2023-01-22T17:45:38.1732561+00:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Failed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="55856235-ad6b-4b3a-bba8-3c0bb00900c1">
      <Output>
        <ErrorInfo>
          <Message>System.AggregateException : One or more errors occurred. (0:The specified resource does not exist.
RequestId:22c8b7f5-8002-0066-0989-2e0427000000
Time:2023-01-22T17:45:38.1178334Z
 The index of the entity that caused the error can be found in FailedTransactionActionIndex.&#xD;
Status: 404 (Not Found)&#xD;
ErrorCode: ResourceNotFound&#xD;
&#xD;
Additional Information:&#xD;
FailedEntity: 0&#xD;
&#xD;
Content:&#xD;
{"odata.error":{"code":"ResourceNotFound","message":{"lang":"en-US","value":"0:The specified resource does not exist.\nRequestId:22c8b7f5-8002-0066-0989-2e0427000000\nTime:2023-01-22T17:45:38.1178334Z"}}}&#xD;
&#xD;
Headers:&#xD;
X-Content-Type-Options: REDACTED&#xD;
Cache-Control: no-cache&#xD;
DataServiceVersion: 3.0;&#xD;
Content-Type: application/json;odata=minimalmetadata;streaming=true;charset=utf-8&#xD;
)&#xD;
---- Azure.Data.Tables.TableTransactionFailedException : 0:The specified resource does not exist.
RequestId:22c8b7f5-8002-0066-0989-2e0427000000
Time:2023-01-22T17:45:38.1178334Z
 The index of the entity that caused the error can be found in FailedTransactionActionIndex.&#xD;
Status: 404 (Not Found)&#xD;
ErrorCode: ResourceNotFound&#xD;
&#xD;
Additional Information:&#xD;
FailedEntity: 0&#xD;
&#xD;
Content:&#xD;
{"odata.error":{"code":"ResourceNotFound","message":{"lang":"en-US","value":"0:The specified resource does not exist.\nRequestId:22c8b7f5-8002-0066-0989-2e0427000000\nTime:2023-01-22T17:45:38.1178334Z"}}}&#xD;
&#xD;
Headers:&#xD;
X-Content-Type-Options: REDACTED&#xD;
Cache-Control: no-cache&#xD;
DataServiceVersion: 3.0;&#xD;
Content-Type: application/json;odata=minimalmetadata;streaming=true;charset=utf-8&#xD;
</Message>
          <StackTrace>   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)&#xD;
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)&#xD;
   at System.Threading.Tasks.Task.Wait(TimeSpan timeout, CancellationToken cancellationToken)&#xD;
   at System.Threading.Tasks.Task.Wait(TimeSpan timeout)&#xD;
   at Orleans.Internal.OrleansTaskExtentions.WaitWithThrow(Task task, TimeSpan timeout) in C:\Users\anna\orleans\src\Orleans.Core\Async\TaskExtensions.cs:line 49&#xD;
   at UnitTests.TimerTests.ReminderTests_Base.Dispose() in C:\Users\anna\orleans\test\TesterInternal\TimerTests\ReminderTests_Base.cs:line 62&#xD;
   at ReflectionAbstractionExtensions.DisposeTestClass(ITest test, Object testClass, IMessageBus messageBus, ExecutionTimer timer, CancellationTokenSource cancellationTokenSource) in /_/src/xunit.execution/Extensions/ReflectionAbstractionExtensions.cs:line 79&#xD;
----- Inner Stack Trace -----&#xD;
   at Azure.Data.Tables.TableRestClient.SendBatchRequestAsync(HttpMessage message, CancellationToken cancellationToken)&#xD;
   at Azure.Data.Tables.TableClient.SubmitTransactionInternalAsync(IEnumerable`1 transactionalBatch, Guid batchId, Guid changesetId, Boolean async, CancellationToken cancellationToken)&#xD;
   at Azure.Data.Tables.TableClient.SubmitTransactionAsync(IEnumerable`1 transactionActions, CancellationToken cancellationToken)&#xD;
   at Orleans.Reminders.AzureStorage.AzureTableDataManager`1.DeleteTableEntriesAsync(List`1 collection) in C:\Users\anna\orleans\src\Azure\Shared\Storage\AzureTableDataManager.cs:line 483&#xD;
   at Orleans.Runtime.ReminderService.RemindersTableManager.DeleteTableEntries() in C:\Users\anna\orleans\src\Azure\Orleans.Reminders.AzureStorage\Storage\RemindersTableManager.cs:line 214&#xD;
   at UnitTests.Grains.ReminderTestGrain2.EraseReminderTable() in C:\Users\anna\orleans\test\Grains\TestInternalGrains\ReminderTestGrain2.cs:line 231&#xD;
   at Orleans.Runtime.TaskRequest.Invoke() in C:\Users\anna\orleans\src\Orleans.Core.Abstractions\Runtime\GrainReference.cs:line 690&#xD;
--- End of stack trace from previous location ---&#xD;
   at Orleans.Serialization.Invocation.ResponseCompletionSource.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token) in C:\Users\anna\orleans\src\Orleans.Serialization\Invocation\ResponseCompletionSource.cs:line 98&#xD;
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.&lt;&gt;c.&lt;.cctor&gt;b__4_0(Object state)</StackTrace>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
  </Results>
  <TestDefinitions>
    <UnitTest name="Tester.AzureUtils.TimerTests.ReminderTests_AzureTable.Rem_Azure_Basic_ListOps" storage="c:\users\anna\orleans\test\extensions\testerazureutils\bin\debug\net7.0\tester.azureutils.dll" id="0ead2138-2212-aba4-35b8-60be64e9d95f">
      <Execution id="55856235-ad6b-4b3a-bba8-3c0bb00900c1" />
      <TestMethod codeBase="C:\Users\anna\orleans\test\Extensions\TesterAzureUtils\bin\Debug\net7.0\Tester.AzureUtils.dll" adapterTypeName="executor://xunit/VsTestRunner2/netcoreapp" className="Tester.AzureUtils.TimerTests.ReminderTests_AzureTable" name="Rem_Azure_Basic_ListOps" />
    </UnitTest>
  </TestDefinitions>
  <TestEntries>
    <TestEntry testId="0ead2138-2212-aba4-35b8-60be64e9d95f" executionId="55856235-ad6b-4b3a-bba8-3c0bb00900c1" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
  </TestEntries>
  <TestLists>
    <TestList name="Results Not in a List" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="All Loaded Results" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <ResultSummary outcome="Failed">
    <Counters total="1" executed="1" passed="0" failed="1" error="0" timeout="0" aborted="0" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" completed="0" inProgress="0" pending="0" />
    <Output>
      <StdOut>[xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.4.5+1caef2f33e (64-bit .NET 7.0.2)&#xD;
[xUnit.net 00:00:01.27]   Discovering: Tester.AzureUtils (method display = ClassAndMethod, method display options = None)&#xD;
[xUnit.net 00:00:01.49]   Discovered:  Tester.AzureUtils (found 246 test cases)&#xD;
[xUnit.net 00:00:01.50]   Starting:    Tester.AzureUtils (parallel test collections = off, max threads = 4)&#xD;
[xUnit.net 00:00:32.16]       System.AggregateException : One or more errors occurred. (0:The specified resource does not exist.
RequestId:22c8b7f5-8002-0066-0989-2e0427000000
Time:2023-01-22T17:45:38.1178334Z
 The index of the entity that caused the error can be found in FailedTransactionActionIndex.&#xD;
[xUnit.net 00:00:32.16]       Status: 404 (Not Found)&#xD;
[xUnit.net 00:00:32.16]       ErrorCode: ResourceNotFound&#xD;
[xUnit.net 00:00:32.16]       &#xD;
[xUnit.net 00:00:32.16]       Additional Information:&#xD;
[xUnit.net 00:00:32.16]       FailedEntity: 0&#xD;
[xUnit.net 00:00:32.16]       &#xD;
[xUnit.net 00:00:32.16]       Content:&#xD;
[xUnit.net 00:00:32.16]       {"odata.error":{"code":"ResourceNotFound","message":{"lang":"en-US","value":"0:The specified resource does not exist.\nRequestId:22c8b7f5-8002-0066-0989-2e0427000000\nTime:2023-01-22T17:45:38.1178334Z"}}}&#xD;
[xUnit.net 00:00:32.16]       &#xD;
[xUnit.net 00:00:32.16]       Headers:&#xD;
[xUnit.net 00:00:32.16]       X-Content-Type-Options: REDACTED&#xD;
[xUnit.net 00:00:32.16]       Cache-Control: no-cache&#xD;
[xUnit.net 00:00:32.16]       DataServiceVersion: 3.0;&#xD;
[xUnit.net 00:00:32.16]       Content-Type: application/json;odata=minimalmetadata;streaming=true;charset=utf-8&#xD;
[xUnit.net 00:00:32.16]       )&#xD;
[xUnit.net 00:00:32.16]       ---- Azure.Data.Tables.TableTransactionFailedException : 0:The specified resource does not exist.
RequestId:22c8b7f5-8002-0066-0989-2e0427000000
Time:2023-01-22T17:45:38.1178334Z
 The index of the entity that caused the error can be found in FailedTransactionActionIndex.&#xD;
[xUnit.net 00:00:32.16]       Status: 404 (Not Found)&#xD;
[xUnit.net 00:00:32.16]       ErrorCode: ResourceNotFound&#xD;
[xUnit.net 00:00:32.16]       &#xD;
[xUnit.net 00:00:32.16]       Additional Information:&#xD;
[xUnit.net 00:00:32.16]       FailedEntity: 0&#xD;
[xUnit.net 00:00:32.16]       &#xD;
[xUnit.net 00:00:32.16]       Content:&#xD;
[xUnit.net 00:00:32.16]       {"odata.error":{"code":"ResourceNotFound","message":{"lang":"en-US","value":"0:The specified resource does not exist.\nRequestId:22c8b7f5-8002-0066-0989-2e0427000000\nTime:2023-01-22T17:45:38.1178334Z"}}}&#xD;
[xUnit.net 00:00:32.16]       &#xD;
[xUnit.net 00:00:32.16]       Headers:&#xD;
[xUnit.net 00:00:32.16]       X-Content-Type-Options: REDACTED&#xD;
[xUnit.net 00:00:32.16]       Cache-Control: no-cache&#xD;
[xUnit.net 00:00:32.16]       DataServiceVersion: 3.0;&#xD;
[xUnit.net 00:00:32.16]       Content-Type: application/json;odata=minimalmetadata;streaming=true;charset=utf-8&#xD;
[xUnit.net 00:00:32.16]       &#xD;
[xUnit.net 00:00:32.16]       Stack Trace:&#xD;
[xUnit.net 00:00:32.16]            at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)&#xD;
[xUnit.net 00:00:32.16]            at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)&#xD;
[xUnit.net 00:00:32.16]            at System.Threading.Tasks.Task.Wait(TimeSpan timeout, CancellationToken cancellationToken)&#xD;
[xUnit.net 00:00:32.16]            at System.Threading.Tasks.Task.Wait(TimeSpan timeout)&#xD;
[xUnit.net 00:00:32.16]         C:\Users\anna\orleans\src\Orleans.Core\Async\TaskExtensions.cs(49,0): at Orleans.Internal.OrleansTaskExtentions.WaitWithThrow(Task task, TimeSpan timeout)&#xD;
[xUnit.net 00:00:32.16]         C:\Users\anna\orleans\test\TesterInternal\TimerTests\ReminderTests_Base.cs(62,0): at UnitTests.TimerTests.ReminderTests_Base.Dispose()&#xD;
[xUnit.net 00:00:32.16]         /_/src/xunit.execution/Extensions/ReflectionAbstractionExtensions.cs(79,0): at ReflectionAbstractionExtensions.DisposeTestClass(ITest test, Object testClass, IMessageBus messageBus, ExecutionTimer timer, CancellationTokenSource cancellationTokenSource)&#xD;
[xUnit.net 00:00:32.16]         ----- Inner Stack Trace -----&#xD;
[xUnit.net 00:00:32.16]            at Azure.Data.Tables.TableRestClient.SendBatchRequestAsync(HttpMessage message, CancellationToken cancellationToken)&#xD;
[xUnit.net 00:00:32.16]            at Azure.Data.Tables.TableClient.SubmitTransactionInternalAsync(IEnumerable`1 transactionalBatch, Guid batchId, Guid changesetId, Boolean async, CancellationToken cancellationToken)&#xD;
[xUnit.net 00:00:32.16]            at Azure.Data.Tables.TableClient.SubmitTransactionAsync(IEnumerable`1 transactionActions, CancellationToken cancellationToken)&#xD;
[xUnit.net 00:00:32.16]         C:\Users\anna\orleans\src\Azure\Shared\Storage\AzureTableDataManager.cs(483,0): at Orleans.Reminders.AzureStorage.AzureTableDataManager`1.DeleteTableEntriesAsync(List`1 collection)&#xD;
[xUnit.net 00:00:32.16]         C:\Users\anna\orleans\src\Azure\Orleans.Reminders.AzureStorage\Storage\RemindersTableManager.cs(214,0): at Orleans.Runtime.ReminderService.RemindersTableManager.DeleteTableEntries()&#xD;
[xUnit.net 00:00:32.16]         C:\Users\anna\orleans\test\Grains\TestInternalGrains\ReminderTestGrain2.cs(231,0): at UnitTests.Grains.ReminderTestGrain2.EraseReminderTable()&#xD;
[xUnit.net 00:00:32.16]         C:\Users\anna\orleans\src\Orleans.Core.Abstractions\Runtime\GrainReference.cs(690,0): at Orleans.Runtime.TaskRequest.Invoke()&#xD;
[xUnit.net 00:00:32.16]         --- End of stack trace from previous location ---&#xD;
[xUnit.net 00:00:32.16]         C:\Users\anna\orleans\src\Orleans.Serialization\Invocation\ResponseCompletionSource.cs(98,0): at Orleans.Serialization.Invocation.ResponseCompletionSource.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)&#xD;
[xUnit.net 00:00:32.16]            at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.&lt;&gt;c.&lt;.cctor&gt;b__4_0(Object state)&#xD;
[xUnit.net 00:00:46.31]   Finished:    Tester.AzureUtils&#xD;
</StdOut>
    </Output>
    <RunInfos>
      <RunInfo computerName="cloudtest-win10" outcome="Min" timestamp="2023-01-22T17:45:38.1650437+00:00">
        <Text>[xUnit.net 00:00:32.16]     Tester.AzureUtils.TimerTests.ReminderTests_AzureTable.Rem_Azure_Basic_ListOps [FAIL]</Text>
      </RunInfo>
      <RunInfo computerName="cloudtest-win10" outcome="Warning" timestamp="2023-01-22T17:45:52.4563756+00:00">
        <Text>Data collector 'Blame' message: All tests finished running, Sequence file will not be generated.</Text>
      </RunInfo>
    </RunInfos>
  </ResultSummary>
</TestRun>