<?xml version="1.0" encoding="utf-8"?>
<TestRun id="7ba0084e-681c-4f7b-b10f-a83c31b43baa" name="anna@cloudtest-win10 2023-01-22 23:21:04" runUser="cloudtest-win10\anna" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <Times creation="2023-01-22T23:21:04.8208894+00:00" queuing="2023-01-22T23:21:04.8208906+00:00" start="2023-01-22T23:19:05.6980494+00:00" finish="2023-01-22T23:21:04.8658377+00:00" />
  <TestSettings name="default" id="e86c0fbb-c402-4675-84f0-abb77cb823f2">
    <Deployment runDeploymentRoot="anna_cloudtest-win10_2023-01-22_23_21_04" />
  </TestSettings>
  <Results>
    <UnitTestResult executionId="cf16c575-fd15-4a3d-81d6-46fc158162ee" testId="e94601a9-8547-590d-a1b8-7b708ab4cf5c" testName="Tester.AzureUtils.AzureTableDataManagerStressTests.AzureTableDataManagerStressTests_ReadAllTableEntities" computerName="cloudtest-win10" duration="00:01:54.2031296" startTime="2023-01-22T23:21:04.4967911+00:00" endTime="2023-01-22T23:21:04.4968352+00:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Failed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="cf16c575-fd15-4a3d-81d6-46fc158162ee">
      <Output>
        <StdOut>Iterations=2000, Batch=2000, Partitions=3&#xD;
AzureTableDataManagerStressTests_ReadAllTableEntities completed. Wrote 2000 entries to 3 partition(s) in 00:01:21.4502979 at 24.554851873660244 RPS&#xD;
AzureTable_ReadAllTableEntities completed. ReadAll 2000 entries in 00:00:10.8117522 at 184.9838918801709 RPS</StdOut>
        <ErrorInfo>
          <Message>System.AggregateException : One or more errors occurred. (0:The specified resource does not exist.
RequestId:6eb49153-9002-0027-77b8-2e5cc3000000
Time:2023-01-22T23:20:55.3888944Z
 The index of the entity that caused the error can be found in FailedTransactionActionIndex.&#xD;
Status: 404 (Not Found)&#xD;
ErrorCode: ResourceNotFound&#xD;
&#xD;
Additional Information:&#xD;
FailedEntity: 0&#xD;
&#xD;
Content:&#xD;
{"odata.error":{"code":"ResourceNotFound","message":{"lang":"en-US","value":"0:The specified resource does not exist.\nRequestId:6eb49153-9002-0027-77b8-2e5cc3000000\nTime:2023-01-22T23:20:55.3888944Z"}}}&#xD;
&#xD;
Headers:&#xD;
X-Content-Type-Options: REDACTED&#xD;
Cache-Control: no-cache&#xD;
DataServiceVersion: 3.0;&#xD;
Content-Type: application/json;odata=minimalmetadata;streaming=true;charset=utf-8&#xD;
)&#xD;
---- Azure.Data.Tables.TableTransactionFailedException : 0:The specified resource does not exist.
RequestId:6eb49153-9002-0027-77b8-2e5cc3000000
Time:2023-01-22T23:20:55.3888944Z
 The index of the entity that caused the error can be found in FailedTransactionActionIndex.&#xD;
Status: 404 (Not Found)&#xD;
ErrorCode: ResourceNotFound&#xD;
&#xD;
Additional Information:&#xD;
FailedEntity: 0&#xD;
&#xD;
Content:&#xD;
{"odata.error":{"code":"ResourceNotFound","message":{"lang":"en-US","value":"0:The specified resource does not exist.\nRequestId:6eb49153-9002-0027-77b8-2e5cc3000000\nTime:2023-01-22T23:20:55.3888944Z"}}}&#xD;
&#xD;
Headers:&#xD;
X-Content-Type-Options: REDACTED&#xD;
Cache-Control: no-cache&#xD;
DataServiceVersion: 3.0;&#xD;
Content-Type: application/json;odata=minimalmetadata;streaming=true;charset=utf-8&#xD;
</Message>
          <StackTrace>   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)&#xD;
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)&#xD;
   at System.Threading.Tasks.Task.Wait(TimeSpan timeout, CancellationToken cancellationToken)&#xD;
   at System.Threading.Tasks.Task.Wait(TimeSpan timeout)&#xD;
   at Orleans.Internal.OrleansTaskExtentions.WaitWithThrow(Task task, TimeSpan timeout) in C:\Users\anna\orleans\src\Orleans.Core\Async\TaskExtensions.cs:line 49&#xD;
   at Tester.AzureUtils.AzureTableDataManagerStressTests.AzureTableDataManagerStressTests_ReadAllTableEntities() in C:\Users\anna\orleans\test\Extensions\TesterAzureUtils\AzureTableDataManagerStressTests.cs:line 99&#xD;
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)&#xD;
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)&#xD;
----- Inner Stack Trace -----&#xD;
   at Azure.Data.Tables.TableRestClient.SendBatchRequestAsync(HttpMessage message, CancellationToken cancellationToken)&#xD;
   at Azure.Data.Tables.TableClient.SubmitTransactionInternalAsync(IEnumerable`1 transactionalBatch, Guid batchId, Guid changesetId, Boolean async, CancellationToken cancellationToken)&#xD;
   at Azure.Data.Tables.TableClient.SubmitTransactionAsync(IEnumerable`1 transactionActions, CancellationToken cancellationToken)&#xD;
   at Orleans.Clustering.AzureStorage.AzureTableDataManager`1.DeleteTableEntriesAsync(List`1 collection) in C:\Users\anna\orleans\src\Azure\Shared\Storage\AzureTableDataManager.cs:line 483&#xD;
   at Orleans.Clustering.AzureStorage.AzureTableDataManager`1.ClearTableAsync() in C:\Users\anna\orleans\src\Azure\Shared\Storage\AzureTableDataManager.cs:line 150</StackTrace>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
  </Results>
  <TestDefinitions>
    <UnitTest name="Tester.AzureUtils.AzureTableDataManagerStressTests.AzureTableDataManagerStressTests_ReadAllTableEntities" storage="c:\users\anna\orleans\test\extensions\testerazureutils\bin\debug\net7.0\tester.azureutils.dll" id="e94601a9-8547-590d-a1b8-7b708ab4cf5c">
      <Execution id="cf16c575-fd15-4a3d-81d6-46fc158162ee" />
      <TestMethod codeBase="C:\Users\anna\orleans\test\Extensions\TesterAzureUtils\bin\Debug\net7.0\Tester.AzureUtils.dll" adapterTypeName="executor://xunit/VsTestRunner2/netcoreapp" className="Tester.AzureUtils.AzureTableDataManagerStressTests" name="AzureTableDataManagerStressTests_ReadAllTableEntities" />
    </UnitTest>
  </TestDefinitions>
  <TestEntries>
    <TestEntry testId="e94601a9-8547-590d-a1b8-7b708ab4cf5c" executionId="cf16c575-fd15-4a3d-81d6-46fc158162ee" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
  </TestEntries>
  <TestLists>
    <TestList name="Results Not in a List" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="All Loaded Results" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <ResultSummary outcome="Failed">
    <Counters total="1" executed="1" passed="0" failed="1" error="0" timeout="0" aborted="0" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" completed="0" inProgress="0" pending="0" />
    <Output>
      <StdOut>[xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.4.5+1caef2f33e (64-bit .NET 7.0.2)&#xD;
[xUnit.net 00:00:01.28]   Discovering: Tester.AzureUtils (method display = ClassAndMethod, method display options = None)&#xD;
[xUnit.net 00:00:01.49]   Discovered:  Tester.AzureUtils (found 246 test cases)&#xD;
[xUnit.net 00:00:01.51]   Starting:    Tester.AzureUtils (parallel test collections = off, max threads = 4)&#xD;
[xUnit.net 00:01:55.80]       System.AggregateException : One or more errors occurred. (0:The specified resource does not exist.
RequestId:6eb49153-9002-0027-77b8-2e5cc3000000
Time:2023-01-22T23:20:55.3888944Z
 The index of the entity that caused the error can be found in FailedTransactionActionIndex.&#xD;
[xUnit.net 00:01:55.80]       Status: 404 (Not Found)&#xD;
[xUnit.net 00:01:55.80]       ErrorCode: ResourceNotFound&#xD;
[xUnit.net 00:01:55.80]       &#xD;
[xUnit.net 00:01:55.80]       Additional Information:&#xD;
[xUnit.net 00:01:55.80]       FailedEntity: 0&#xD;
[xUnit.net 00:01:55.80]       &#xD;
[xUnit.net 00:01:55.80]       Content:&#xD;
[xUnit.net 00:01:55.80]       {"odata.error":{"code":"ResourceNotFound","message":{"lang":"en-US","value":"0:The specified resource does not exist.\nRequestId:6eb49153-9002-0027-77b8-2e5cc3000000\nTime:2023-01-22T23:20:55.3888944Z"}}}&#xD;
[xUnit.net 00:01:55.80]       &#xD;
[xUnit.net 00:01:55.80]       Headers:&#xD;
[xUnit.net 00:01:55.80]       X-Content-Type-Options: REDACTED&#xD;
[xUnit.net 00:01:55.80]       Cache-Control: no-cache&#xD;
[xUnit.net 00:01:55.80]       DataServiceVersion: 3.0;&#xD;
[xUnit.net 00:01:55.80]       Content-Type: application/json;odata=minimalmetadata;streaming=true;charset=utf-8&#xD;
[xUnit.net 00:01:55.80]       )&#xD;
[xUnit.net 00:01:55.80]       ---- Azure.Data.Tables.TableTransactionFailedException : 0:The specified resource does not exist.
RequestId:6eb49153-9002-0027-77b8-2e5cc3000000
Time:2023-01-22T23:20:55.3888944Z
 The index of the entity that caused the error can be found in FailedTransactionActionIndex.&#xD;
[xUnit.net 00:01:55.80]       Status: 404 (Not Found)&#xD;
[xUnit.net 00:01:55.80]       ErrorCode: ResourceNotFound&#xD;
[xUnit.net 00:01:55.80]       &#xD;
[xUnit.net 00:01:55.80]       Additional Information:&#xD;
[xUnit.net 00:01:55.80]       FailedEntity: 0&#xD;
[xUnit.net 00:01:55.80]       &#xD;
[xUnit.net 00:01:55.80]       Content:&#xD;
[xUnit.net 00:01:55.80]       {"odata.error":{"code":"ResourceNotFound","message":{"lang":"en-US","value":"0:The specified resource does not exist.\nRequestId:6eb49153-9002-0027-77b8-2e5cc3000000\nTime:2023-01-22T23:20:55.3888944Z"}}}&#xD;
[xUnit.net 00:01:55.80]       &#xD;
[xUnit.net 00:01:55.80]       Headers:&#xD;
[xUnit.net 00:01:55.80]       X-Content-Type-Options: REDACTED&#xD;
[xUnit.net 00:01:55.80]       Cache-Control: no-cache&#xD;
[xUnit.net 00:01:55.80]       DataServiceVersion: 3.0;&#xD;
[xUnit.net 00:01:55.80]       Content-Type: application/json;odata=minimalmetadata;streaming=true;charset=utf-8&#xD;
[xUnit.net 00:01:55.80]       &#xD;
[xUnit.net 00:01:55.80]       Stack Trace:&#xD;
[xUnit.net 00:01:55.80]            at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)&#xD;
[xUnit.net 00:01:55.80]            at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)&#xD;
[xUnit.net 00:01:55.80]            at System.Threading.Tasks.Task.Wait(TimeSpan timeout, CancellationToken cancellationToken)&#xD;
[xUnit.net 00:01:55.80]            at System.Threading.Tasks.Task.Wait(TimeSpan timeout)&#xD;
[xUnit.net 00:01:55.80]         C:\Users\anna\orleans\src\Orleans.Core\Async\TaskExtensions.cs(49,0): at Orleans.Internal.OrleansTaskExtentions.WaitWithThrow(Task task, TimeSpan timeout)&#xD;
[xUnit.net 00:01:55.80]         C:\Users\anna\orleans\test\Extensions\TesterAzureUtils\AzureTableDataManagerStressTests.cs(99,0): at Tester.AzureUtils.AzureTableDataManagerStressTests.AzureTableDataManagerStressTests_ReadAllTableEntities()&#xD;
[xUnit.net 00:01:55.80]            at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)&#xD;
[xUnit.net 00:01:55.80]            at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)&#xD;
[xUnit.net 00:01:55.80]         ----- Inner Stack Trace -----&#xD;
[xUnit.net 00:01:55.80]            at Azure.Data.Tables.TableRestClient.SendBatchRequestAsync(HttpMessage message, CancellationToken cancellationToken)&#xD;
[xUnit.net 00:01:55.80]            at Azure.Data.Tables.TableClient.SubmitTransactionInternalAsync(IEnumerable`1 transactionalBatch, Guid batchId, Guid changesetId, Boolean async, CancellationToken cancellationToken)&#xD;
[xUnit.net 00:01:55.80]            at Azure.Data.Tables.TableClient.SubmitTransactionAsync(IEnumerable`1 transactionActions, CancellationToken cancellationToken)&#xD;
[xUnit.net 00:01:55.80]         C:\Users\anna\orleans\src\Azure\Shared\Storage\AzureTableDataManager.cs(483,0): at Orleans.Clustering.AzureStorage.AzureTableDataManager`1.DeleteTableEntriesAsync(List`1 collection)&#xD;
[xUnit.net 00:01:55.80]         C:\Users\anna\orleans\src\Azure\Shared\Storage\AzureTableDataManager.cs(150,0): at Orleans.Clustering.AzureStorage.AzureTableDataManager`1.ClearTableAsync()&#xD;
[xUnit.net 00:01:55.80]       Output:&#xD;
[xUnit.net 00:01:55.80]         Iterations=2000, Batch=2000, Partitions=3&#xD;
[xUnit.net 00:01:55.80]         AzureTableDataManagerStressTests_ReadAllTableEntities completed. Wrote 2000 entries to 3 partition(s) in 00:01:21.4502979 at 24.554851873660244 RPS&#xD;
[xUnit.net 00:01:55.80]         AzureTable_ReadAllTableEntities completed. ReadAll 2000 entries in 00:00:10.8117522 at 184.9838918801709 RPS&#xD;
[xUnit.net 00:01:55.84]   Finished:    Tester.AzureUtils&#xD;
</StdOut>
    </Output>
    <RunInfos>
      <RunInfo computerName="cloudtest-win10" outcome="Min" timestamp="2023-01-22T23:21:04.4907810+00:00">
        <Text>[xUnit.net 00:01:55.80]     Tester.AzureUtils.AzureTableDataManagerStressTests.AzureTableDataManagerStressTests_ReadAllTableEntities [FAIL]</Text>
      </RunInfo>
      <RunInfo computerName="cloudtest-win10" outcome="Warning" timestamp="2023-01-22T23:21:04.6668639+00:00">
        <Text>Data collector 'Blame' message: All tests finished running, Sequence file will not be generated.</Text>
      </RunInfo>
    </RunInfos>
  </ResultSummary>
</TestRun>